### ISSUE TITLE
Incorporate CI/CD in options in project build + docs

### ISSUE THREAD

**Issue by andrewconnell** [pnp/generator-teams#99]
**Is your feature request related to a problem? Please describe.**

Today the generator assumes you want to deploy the project to an Azure web app using the included **.deployment** file. This doesn't account for other deployment options (to other platforms or using Azure DevOps).

**Describe the solution you'd like**

Option in the generator to prompt "do you to deploy to Azure web apps?" or "do you want to deploy using Azure DevOps?" in the long term. These options would add either a **.deployment** or **azure-pipelines.yml** file to the root.

But in the short term, I propose the following to ensure the process is solid:
- [ ] remove **.deployment** file from the generator
- [ ] add docs on "How to deploy to Azure web apps" that explain how to add the **.deployment file**
- [ ] add docs on "How to deploy with Azure DevOps Pipelines" that explains how to set it up by adding a **azure-pipelines.yml** file and configuring a pipeline

Down the road, we can add the options to the generator that can add these files to a project, either a new project or an existing project

*Feel free to assign to me*

**Comment by webdes03** [comment]
Can anyone provide basic steps to getting this to work with CI/CD? I've got my pipelines yaml all setup and it's generating the zip archive for deployment, but it appears to only be serving the raw HTML pages after deployment. None of the express routes defined in server.ts for the SSO are available, and whenever I try to run `node server.js` manually through Kudu, I get an error saying express isn't found, even though it is part of the package.json. I suspect I'm just missing some silly little piece, but I can't get it to work :-(.

**Comment by wictorwilen** [comment]
@webdes03 this is a pipeline I use for Azure DevOps

``` yaml
variables:
  vmImageName: "ubuntu-latest"
  tag: "$(Build.BuildId)"
  appName: "my-teams-webapp"
  subscription: "Microsoft Azure Enterprise(00000000-0000-0000-0000-000000000000)"

trigger:
  - main
  - dev

stages:
  - stage: Build
    displayName: Build and package
    jobs:
      - job: Build
        displayName: Build and package
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            displayName: Use Node 12.x
            inputs:
              versionSpec: "12.x"
          - script: |
              sudo curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | sudo bash -s -- -b /usr/local/bin
            displayName: Install node-prune
          - script: |
              npm install
            displayName: npm install
          - script: |
              npm run build
            displayName: npm run build
          - script: |
              npm prune --production
            displayName: npm prune
          - script: |
              /usr/local/bin/node-prune
            displayName: execute node-prune
          - task: CopyFiles@2
            displayName: Only publish files needed for runtime
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: |
                dist/**
                library/**
                package.json
                node_modules/**
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(Build.ArtifactStagingDirectory)"
              includeRootFolder: false
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(appName).zip"
              archiveType: zip
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/$(appName).zip"

  - stage: Deploy
    displayName: Deploy to App Service (dev)
    dependsOn: Build
    jobs:
      - deployment: deployDev
        displayName: "Deploy to dev"
        environment: knok-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@1
                  inputs:
                    downloadPath: "$(System.DefaultWorkingDirectory)"
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(subscription)
                    appType: "webAppLinux"
                    appName: $(appName)
                    runtimeStack: "NODE|12-lts"
                    startUpCommand: "node dist/server.js"
```
